source commonComponentCompile.do
source SquareRootCompile.do
source AdiabaticProcessorCompile.do
source pA0updaterCompile.do
source SumNSpinsCompile.do
source NSpinSolverCompile.do
vcom SimulatedBifurcationMachine3Spin.vhd
vcom SpinMachine3.vhd
vcom ../common_component/clock_gen.vhd
vcom ../common_component/reset_gen.vhd
vcom TestbenchSaveVersion3Spin.vhd