source commonComponentCompile.do
source SquareRootCompile.do
source AdiabaticProcessorCompile.do
source pA0updaterCompile.do
source SumNSpinsCompile.do
source NSpinSolverCompile.do
source TestbenchCompile5.do